const state = {
  view: 'marketplace',
  context: 'Guest · Oceanami',
  request: { id:'RQ-104', source:'Direct', status:'NONE', hostDecision:'PENDING' },
  payment: { status:'NOT_STARTED' },
  booking: { status:'NONE' },
  stay: { status:'NONE', readiness:'NOT_READY', arrival:'NOT_OBSERVED', checkout:false, completion:false },
  access: { mode:'credential', account:false },
  saleRequestCreated:false,
  incident: { status:'NONE' },
  hold: { status:'NONE', revalidated:false },
  external: { reported:false, fact:false, commitment:false, stay:false },
  conflict: { resolved:false }
};
const $ = (s)=>document.querySelector(s);
const escapeHtml=(s)=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function status(text, kind='current'){ return `<span class="status ${kind}">${text}</span>`; }
function button(label, action, cls='secondary', disabled=false){ return `<button class="${cls}${disabled?' disabled':''}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`; }
function pageHead(kicker,title,sub,context='Guest · Oceanami'){ return `<div class="page-head"><div><div class="kicker">${kicker}</div><h1 class="page-title">${title}</h1><p class="page-sub">${sub}</p></div><div class="context-card"><div class="label">Working context</div><div class="value">${context}</div><span class="muted">Perspective / scope only · authority is evaluated per action</span></div></div>`; }
function line(k,v){ return `<div class="line"><span class="key">${k}</span><span class="value">${v}</span></div>`; }
function authority(items){ return `<div>${items.map(x=>`<span class="authority ${x[1]||''}">${x[0]}</span>`).join('')}</div>`; }
function journey(){
  const stages=[['01','DISCOVER',true],['02','REQUEST',state.request.status!=='NONE'],['03','DECISION',state.request.hostDecision==='ACCEPTED'],['04','BOOKING',state.booking.status==='CONFIRMED'],['05','STAY',state.stay.status!=='NONE'],['06','ARRIVAL',state.stay.arrival==='OBSERVED'],['07','CHECK-IN',state.stay.status==='CHECKED_IN'],['08','CHECK-OUT',state.stay.checkout],['09','COMPLETE',state.stay.completion]];
  return `<div class="journey">${stages.map((s,i)=>`<div class="step ${s[2]?'done':''} ${!s[2]&&i===stages.findIndex(x=>!x[2])?'current':''}"><div class="step-dot">${s[0]}</div><div class="step-label">${s[1]}</div><div class="step-note">${s[2]?'reached':'next truth'}</div></div>`).join('')}</div>`;
}
function truthOverview(){
 return `<div class="section-label"><h2>One canonical spine, separate objects</h2><span class="muted">same truth, contextual projections</span></div>${journey()}<div class="grid three">
  <div class="card"><div class="label">Request</div><div class="object-title">${state.request.status==='NONE'?'Not created':state.request.id}</div><p>${state.request.source} intent · inventory is not reserved by request.</p>${status(state.request.status==='NONE'?'NOT CREATED':state.request.status==='CREATED'?'CREATED':state.request.hostDecision,'current')}</div>
  <div class="card"><div class="label">Booking</div><div class="object-title">${state.booking.status==='CONFIRMED'?'BK-084':'Not yet'}</div><p>Commercial commitment only after applicable confirmation conditions pass.</p>${status(state.booking.status==='CONFIRMED'?'CONFIRMED':'UNCONFIRMED',state.booking.status==='CONFIRMED'?'current':'pending')}</div>
  <div class="card"><div class="label">Stay</div><div class="object-title">${state.stay.status==='NONE'?'Not yet':'ST-084'}</div><p>Operational lifecycle is evaluated separately from Booking and Payment.</p>${status(state.stay.status==='NONE'?'NOT STARTED':state.stay.status,state.stay.status==='CHECKED_IN'?'current':'pending')}</div>
 </div>`;
}
function marketplace(){ return `${pageHead('Public marketplace','Find the stay that fits the destination','A small Oceanami slice: accommodation discovery, transparent intent and a request that stays a Request until authoritative conditions pass.')}
 <div class="grid two"><div class="card" style="padding:0;overflow:hidden"><div style="height:210px;background:linear-gradient(140deg,#c4b6a2,#847b72 55%,#4d5962);position:relative"><div style="position:absolute;inset:auto 18px 16px;color:#fff"><div class="eyebrow" style="color:#fff;opacity:.8">Oceanami · private villa</div><div class="object-title" style="font-size:29px">Villa 03</div></div></div><div style="padding:18px"><div class="pill-row"><span class="chip">4 guests</span><span class="chip">2 bedrooms</span><span class="chip">Ocean view</span></div><p style="margin:13px 0 0;color:var(--muted)">A destination listing with visible provenance, context-aware bookability and no hidden operational truth.</p><div class="actions">${button('View accommodation','property','primary')} ${button('Start a request','start-request','secondary')}</div></div></div>
 <div class="card"><div class="label">Why this is not a booking</div><h3 style="margin-top:7px">Guest intent creates a Request</h3><p>The next action asks for a stay window and guest count. Inventory is evaluated when the Host decides; the Request itself does not reserve Unit × Time.</p><div class="notice"><div>◌</div><div><strong>Contextual bookability</strong><p>Available for this Guest view is a derived projection, not a universal Available / Unavailable switch.</p></div></div>${authority([['Can See','can'],['Can Initiate','can'],['Cannot Act as Host','cannot']])}</div></div>
 ${truthOverview()}<div class="section-label"><h2>Attention is a projection</h2><span class="muted">links to underlying truth</span></div><div class="attention-list">${attentionItems()}</div>`; }
function attentionItems(){
 const arr=[]; if(state.request.status==='CREATED'&&state.request.hostDecision==='PENDING')arr.push(['Request needs decision','RQ-104 · Host context','host']); if(state.payment.status==='UNKNOWN')arr.push(['Payment UNKNOWN','Authoritative outcome needs reconciliation','admin']); if(state.conflict.resolved===false)arr.push(['Inventory conflict','Villa 03 · 13 Aug · no universal winner','destination']); if(state.hold.status==='OPEN')arr.push(['Protective Hold review','Evidence and revalidation required','butler']); if(state.external.reported&&!state.external.fact)arr.push(['External evidence needs validation','Report ER-019 · not Stayora commerce','destination']); if(state.stay.status==='DID_NOT_OCCUR')arr.push(['DID_NOT_OCCUR evaluation','Explicit authorized evaluation recorded','butler']); if(!arr.length)return '<div class="notice"><div>✓</div><div><strong>No new attention projection</strong><p>Underlying truth is stable in this prototype snapshot.</p></div></div>'; return arr.map(x=>`<div class="attention"><div class="left"><div class="icon">!</div><div><strong>${x[0]}</strong><span>${x[1]}</span></div></div><button class="quiet" data-view="${x[2]}">Open</button></div>`).join('');
}
function property(){ return `${pageHead('Accommodation detail','Villa 03 · Oceanami','The detail view makes provenance and bookability legible before the Guest starts an intent.')}
 <div class="grid two"><div class="panel"><div class="label">Listing projection</div><div class="object-title">Private villa near the beach</div><p class="page-sub">The listing describes accommodation; it does not imply Owner authority, Verified status or a guaranteed Booking.</p><div class="pill-row" style="margin-top:15px"><span class="chip">Oceanami</span><span class="chip">4 guests</span><span class="chip">Guest-facing</span><span class="chip">Quality evidence visible</span></div><div class="actions">${button('Start a request','start-request','primary')} ${button('Back to marketplace','marketplace','secondary')}</div></div><div class="card"><div class="label">Inventory projection</div>${line('12 Aug','Derived availability')} ${line('13 Aug',status('Conflict · 2 truths','conflict'))} ${line('14 Aug',status('Contextual bookability','current'))}<div class="meta">No universal conflict precedence is implied. Open Inventory to inspect source and basis.</div>${button('Inspect Inventory','destination','secondary')}</div></div>
 <div class="panel"><div class="label">Trust / provenance</div><div class="grid three"><div><strong>Stayora Verified</strong><p class="muted">Property-supply quality assurance. Not identity verification.</p></div><div><strong>Reputation</strong><p class="muted">Responsibility follows the actor/context that produced the stay.</p></div><div><strong>External evidence</strong><p class="muted">May inform Inventory truth without fabricating Stayora commerce.</p></div></div></div>`; }
function requestComposer(source='Direct'){ return `${pageHead(source==='Sale'?'Sale-assisted discovery':'Guest intent','Create a Request','Request is a first-class object. Acceptance is a Host decision; confirmation is a separate canonical condition.')}
 <div class="grid two"><div class="panel"><div class="label">New Request · illustrative</div><div class="form-row"><div class="field"><label>Stay window</label><input value="12–15 Aug" readonly></div><div class="field"><label>Guests</label><input value="2 adults" readonly></div></div><div class="form-row" style="margin-top:10px"><div class="field"><label>Source</label><input value="${source==='Sale'?'Sale-assisted · SA-014':'Direct guest'}" readonly></div><div class="field"><label>Unit</label><input value="Villa 03 · Oceanami" readonly></div></div><div class="notice"><div>i</div><div><strong>Inventory not reserved</strong><p>Creating this Request records intent and creates a host-visible truth. It does not create Booking BK-084.</p></div></div><div class="actions">${button('Create Request','create-request','primary')} ${button('Cancel','marketplace','secondary')}</div></div><div class="card"><div class="label">Authority at this moment</div>${authority([['Can Initiate · Guest','can'],['Sale can initiate where allowed','can'],['Cannot Accept','cannot'],['Authority to confirm · unknown','unknown']])}<p>Working Context describes who is acting and which resource is in scope; it does not elevate the actor.</p></div></div>`; }
function host(){ const created=state.request.status!=='NONE'; return `${pageHead('Host workspace','Decide on the Request','The Host sees the same Request truth. Accepting is an authorized decision; it is not Booking confirmation.')}
 <div class="grid two"><div class="panel"><div class="label">Request projection · Host context</div><div class="object-title">${created?state.request.id:'No active Request'}</div>${created?`${line('Source',state.request.source==='Sale'?'Sale-assisted · SA-014':'Direct guest')} ${line('Stay window','12–15 Aug')} ${line('Host decision',status(state.request.hostDecision,state.request.hostDecision==='ACCEPTED'?'current':'pending'))} ${line('Inventory effect',state.request.hostDecision==='ACCEPTED'?'Applicable commitment evaluation':'No reservation')}`:'<p class="muted">Create a Request from Marketplace or Sale workspace to continue the spine.</p>'}<div class="actions">${created&&state.request.hostDecision==='PENDING'?button('Accept Request','accept-request','primary'):''} ${created&&state.request.hostDecision==='ACCEPTED'?button('Evaluate confirmation conditions','evaluate-confirmation','primary'):''} ${created&&state.request.hostDecision==='ACCEPTED'?button('Reject Request','reject-request','danger'):''}</div></div><div class="card"><div class="label">Authority boundary</div>${authority([['Can See · Request','can'],['Can Act · Host authority','can'],['Sale attribution ≠ authority','cannot'],['Booking confirmation · condition-bound','unknown']])}<p>The prototype makes the consequential action re-check current Request truth and Host authority.</p></div></div>
 ${created?`<div class="panel"><div class="label">Confirmation conditions</div><div class="grid three"><div><strong>Request accepted</strong><p class="muted">${status(state.request.hostDecision==='ACCEPTED'?'PASS':'PENDING',state.request.hostDecision==='ACCEPTED'?'current':'pending')}</p></div><div><strong>Payment condition</strong><p class="muted">${status(state.payment.status==='SUCCEEDED'?'PROVEN':state.payment.status==='UNKNOWN'?'UNKNOWN':'UNPROVEN',state.payment.status==='SUCCEEDED'?'success':state.payment.status==='UNKNOWN'?'unknown':'pending')}</p></div><div><strong>Booking</strong><p class="muted">${status(state.booking.status==='CONFIRMED'?'CONFIRMED':'UNCONFIRMED',state.booking.status==='CONFIRMED'?'current':'pending')}</p></div></div><div class="meta">Payment SUCCEEDED is an interaction outcome; it does not automatically become Booking CONFIRMED.</div></div>`:''}`; }
function sale(){return `${pageHead('Sale workspace','Assist discovery without inheriting Host authority','Sale can initiate a Request where allowed and receives attribution. The canonical Request / Booking / Stay objects remain shared.')}
 <div class="grid two"><div class="panel"><div class="label">Guest need · Sale context</div><div class="object-title">Oceanami · 12–15 Aug</div><p>Sale SA-014 is helping a Guest compare suitable accommodation. The action creates the same Request object used by Direct Guest flow.</p>${authority([['Can See · scoped inventory','can'],['Can Initiate · where allowed','can'],['Cannot Accept Request','cannot'],['Cannot set Owner economics','cannot']])}<div class="actions">${button('Create Sale-assisted Request','sale-request','primary')} ${button('Open Host projection','host','secondary')}</div></div><div class="card"><div class="label">Attribution stays attribution</div>${line('Source','Sale-assisted')} ${line('Sale','SA-014 · Linh')} ${line('Request object','RQ-104 · shared truth')} ${line('Authority','Host / applicable policy')}<div class="notice"><div>↗</div><div><strong>Convergent path</strong><p>There is no DirectBooking or SaleBooking variant. Source metadata does not change lifecycle semantics.</p></div></div></div></div>
 <div class="panel"><div class="label">Sale attention</div><div class="notice"><div>i</div><div><strong>Request status is authoritative elsewhere</strong><p>Sale can see the scoped projection and explain progress. Host authority remains the decision boundary.</p></div></div></div>`; }
function guest(){const stayExists=state.stay.status!=='NONE';return `${pageHead('Guest Stay Access','Your Stay Hub','The same Stay projection is available through a scoped credential or a legitimate Guest Identity association. No Guest account is required for the credential path.')}
 <div class="grid two"><div class="panel"><div class="label">Access path</div><div class="pill-row"><button class="chip ${state.access.mode==='credential'?'active-chip':''}" data-action="access-credential">Scoped Stay Access</button><button class="chip ${state.access.mode==='identity'?'active-chip':''}" data-action="access-identity">Authenticated Guest Identity</button></div><div class="notice" style="margin-top:16px"><div>◫</div><div><strong>${state.access.mode==='credential'?'Credential projection':'Identity + legitimate Stay association'}</strong><p>${state.access.mode==='credential'?'A neutral prototype credential grants scoped visibility only. It is not authority.':'Authenticated identity is associated with ST-084; scope remains limited to the legitimate Stay.'}</p></div></div>${line('Account required',state.access.mode==='credential'?'No':'Yes')} ${line('Credential',state.access.mode==='credential'?'Scoped · illustrative':'Not used')} ${line('Authority',status('Credential ≠ authority','info'))}</div><div class="card"><div class="label">Stay state</div><div class="object-title">${stayExists?'ST-084':'No Stay yet'}</div>${line('Booking',state.booking.status==='CONFIRMED'?status('CONFIRMED','current'):status('UNCONFIRMED','pending'))}${line('Stay',status(state.stay.status==='NONE'?'NOT CREATED':state.stay.status,state.stay.status==='CHECKED_IN'?'current':'pending'))}${line('Arrival observation',state.stay.arrival==='OBSERVED'?status('OBSERVED','observed'):status('NOT OBSERVED','pending'))}<div class="actions">${button('Open Butler projection','butler','secondary')} ${button('Open operational truth','destination','secondary')}</div></div></div>
 <div class="panel"><div class="label">Guest-facing progression</div>${journey()}<div class="meta">SCHEDULED, CHECKED_IN, CHECKED_OUT and COMPLETED are projections of Stay lifecycle. Access does not mutate state.</div></div>`; }
function butler(){return `${pageHead('Operations · Butler','Prepare, observe, check in, check out','Assignment provides operational context. Authority is evaluated for each consequential action.')}
 <div class="grid two"><div class="panel"><div class="label">Stay operations · ST-084</div><div class="object-title">Villa 03 · 12–15 Aug</div>${line('Stay',status(state.stay.status==='NONE'?'NOT CREATED':state.stay.status,state.stay.status==='CHECKED_IN'?'current':'pending'))}${line('Preparation',state.stay.readiness==='READY'?status('READY milestone','current'):status('NOT RECORDED','pending'))}${line('Arrival observation',state.stay.arrival==='OBSERVED'?status('OBSERVED','observed'):status('NOT OBSERVED','pending'))}${line('Checkout',state.stay.checkout?status('CHECKED_OUT','current'):status('NOT YET','pending'))}${line('Completion',state.stay.completion?status('COMPLETED','current'):status('EVALUATION PENDING','pending'))}<div class="actions">${button('Record READY milestone','ready','secondary',state.stay.status!=='SCHEDULED'||state.stay.readiness==='READY')} ${button('Record arrival observation','arrival','secondary',state.stay.status!=='SCHEDULED'||state.stay.arrival==='OBSERVED')} ${button('Authorize Check-in','checkin','primary',state.stay.status!=='SCHEDULED'||state.stay.arrival!=='OBSERVED')} ${button('Authorize Checkout','checkout','secondary',state.stay.status!=='CHECKED_IN'||state.stay.checkout)} ${button('Evaluate completion','complete','secondary',!state.stay.checkout||state.stay.completion)} ${button('Evaluate DID_NOT_OCCUR','did-not-occur','danger',state.stay.status==='CHECKED_IN'||state.stay.checkout||state.stay.completion)}</div></div><div class="card"><div class="label">Authority and assignment</div>${authority([['Assigned Butler · Can See','can'],['Assignment ≠ authority','cannot'],['Can Act if capability scoped','can'],['Guest credential ≠ authority','cannot']])}<p>Arrival observation is evidence. It does not silently become Check-in. Checkout is an operational action; Completion is a separate evaluation.</p><div class="notice"><div>!</div><div><strong>Operational truth stays explicit</strong><p>Completion does not automatically release Inventory in this prototype.</p></div></div></div></div>
 <div class="panel"><div class="label">Exception branch</div><div class="grid two"><div><strong>DID_NOT_OCCUR</strong><p class="muted">Requires explicit authorized evaluation. The prototype never transitions here by elapsed time.</p></div><div class="actions" style="align-items:center">${button('Record explicit DID_NOT_OCCUR','did-not-occur','danger',state.stay.status==='CHECKED_IN'||state.stay.checkout||state.stay.completion)}</div></div></div>`; }
function destination(){return `${pageHead('Operations · Destination / BQL','Shared truth and operational attention','A dense view for Inventory, evidence and protective intervention. BQL visibility does not grant universal authority.')}
 <div class="grid two"><div class="panel"><div class="label">Working context</div><div class="object-title">Oceanami · Villa 03</div>${authority([['Can See · destination scope','can'],['Can Initiate · evidence','can'],['Can Act · only if scoped','unknown'],['No universal conflict winner','cannot']])}<div class="meta">BQL context is a visibility and operational scope; it is not a blanket permission.</div></div><div class="card"><div class="label">Attention projections</div><div class="attention-list">${attentionItems()}</div></div></div>
 <div class="section-label"><h2>Inventory truth</h2><span class="muted">Unit × Time · provenance visible</span></div><div class="panel calendar"><table><thead><tr><th>Unit / basis</th><th>12 Aug</th><th>13 Aug</th><th>14 Aug</th><th>15 Aug</th></tr></thead><tbody><tr><td><strong>Villa 03</strong><div class="meta">Oceanami · scoped view</div></td><td><div class="date">12</div><div class="cell-label">Confirmed accommodation commitment</div><div class="cell-meta">BK-084 · source: Stayora</div></td><td class="conf"><div class="date">13</div><div class="cell-label">CONFLICT · 2 truths</div><div class="cell-meta">Maintenance Block + External-backed Commitment · no universal winner</div></td><td><div class="date">14</div><div class="cell-label">Temporary exclusive commitment</div><div class="cell-meta">RQ-104 · pending condition</div></td><td class="hold"><div class="date">15</div><div class="cell-label">Emergency Protective Hold</div><div class="cell-meta">Attention + escalation required</div></td></tr><tr><td><strong>Villa 04</strong><div class="meta">same property scope</div></td><td class="past"><div class="date">12</div><div class="cell-label">Past date</div><div class="cell-meta">Historical projection</div></td><td><div class="date">13</div><div class="cell-label">Derived Availability</div><div class="cell-meta">Bookability is actor/contextual</div></td><td><div class="date">14</div><div class="cell-label">Owner Block</div><div class="cell-meta">Provenance visible</div></td><td><div class="date">15</div><div class="cell-label">Maintenance Block</div><div class="cell-meta">Not a generic unavailable state</div></td></tr></tbody></table></div>
 <div class="grid three"><div class="card"><div class="label">Incident / evidence</div><h3>${state.incident.status==='OPEN'?'Observation recorded':'No incident recorded'}</h3><p>Observation → Incident/evidence → Attention → escalation → authorized evaluation.</p>${state.incident.status==='OPEN'?status('OPEN','observed'):status('NOT RECORDED','pending')}<div class="actions">${button('Record observation','incident','secondary',state.incident.status==='OPEN')}</div></div><div class="card"><div class="label">Emergency Protective Hold</div><h3>Protective intervention</h3><p>Hold is a scoped protection mechanism; it is distinct from Conflict, Maintenance Block and Booking cancellation.</p>${state.hold.status==='OPEN'?status('PROTECTIVE HOLD OPEN','protective'):status('NOT OPEN','pending')}<div class="actions">${button(state.hold.status==='OPEN'?'Revalidate hold':'Create protective hold','hold',state.hold.status==='OPEN'?'secondary':'primary',state.hold.status==='OPEN'&&state.hold.revalidated)} ${state.hold.status==='OPEN'?button('Revalidate','revalidate','secondary',state.hold.revalidated):''}</div></div><div class="card"><div class="label">Conflict entry</div><h3>Maintenance Block + External-backed Commitment</h3><p>Competing legitimate truths are both visible. Resolution is an explicit entry, never an implied universal precedence.</p>${status(state.conflict.resolved?'RESOLUTION RECORDED':'NO WINNER','conflict')}<div class="actions">${button('Open resolution entry','resolution','secondary',state.conflict.resolved)}</div></div></div>`; }
function admin(){return `${pageHead('Stayora Admin','Reconciliation and exception view','Admin sees exceptional truth for reconciliation. This prototype does not grant a universal override or invent a settlement decision.')}
 <div class="grid two"><div class="panel"><div class="label">Payment reconciliation</div><div class="object-title">Payment attempt · PA-084</div>${line('Outcome',state.payment.status==='UNKNOWN'?status('UNKNOWN','unknown'):status(state.payment.status==='SUCCEEDED'?'SUCCEEDED':'NOT STARTED',state.payment.status==='SUCCEEDED'?'success':'pending'))}${line('Booking',status(state.booking.status==='CONFIRMED'?'CONFIRMED':'UNCONFIRMED',state.booking.status==='CONFIRMED'?'current':'pending'))}<div class="notice unknown"><div>?</div><div><strong>UNKNOWN is not FAILED or SUCCESS</strong><p>Processing may have completed, but the authoritative outcome cannot currently be established. Duplicate action is blocked until reconciliation.</p></div></div><div class="actions">${button('Simulate payment UNKNOWN','payment-unknown','primary',state.payment.status==='UNKNOWN')} ${button('Record payment succeeded','payment-success','secondary',state.payment.status==='SUCCEEDED')} ${button('Evaluate confirmation conditions','evaluate-confirmation','secondary',state.request.hostDecision!=='ACCEPTED'||state.payment.status==='UNKNOWN')}</div></div><div class="card"><div class="label">External Accommodation</div><div class="object-title">ER-019 · partner channel report</div>${line('Report / evidence',state.external.reported?status('RECORDED','observed'):status('NOT RECORDED','pending'))}${line('External Fact',state.external.fact?status('VALIDATED','current'):status('NOT VALIDATED','pending'))}${line('Inventory',state.external.commitment?status('EXTERNAL-BACKED COMMITMENT','current'):status('NO COMMITMENT','pending'))}${line('Stay',state.external.stay?status('LEGITIMATE STAY','current'):status('NONE','pending'))}<div class="actions">${button('Record external report','external-report','secondary',state.external.reported)} ${button('Validate External Accommodation Fact','external-fact','secondary',!state.external.reported||state.external.fact)} ${button('Evaluate Inventory implication','external-commitment','secondary',!state.external.fact||state.external.commitment)} ${button('Create legitimate Stay projection','external-stay','secondary',!state.external.commitment||state.external.stay)}</div><div class="meta">No Stayora Request, Booking, Payment, commission or settlement is fabricated for this external path.</div></div></div>
 <div class="panel"><div class="label">Reconciliation boundaries</div><div class="grid three"><div><strong>Can See</strong><p class="muted">Exception evidence and provenance.</p></div><div><strong>Can Act if Authorized</strong><p class="muted">Record/validate within scoped capability.</p></div><div><strong>Does not mean</strong><p class="muted">Universal conflict winner or commercial override.</p></div></div></div>`; }
function validation(){return `${pageHead('Founder validation package','What this prototype proves','Use the navigation and action buttons to walk the vertical slice. This panel records what is demonstrated in the local simulation, not product acceptance.')}
 <div class="validation-grid"><div class="metric"><strong>9</strong><span>spine stages</span></div><div class="metric"><strong>9</strong><span>required scenarios</span></div><div class="metric"><strong>7</strong><span>canonical surfaces</span></div><div class="metric"><strong>0</strong><span>production integrations</span></div></div>
 <div class="section-label"><h2>Validation questions</h2><span class="muted">founder / product architect review</span></div><div class="panel"><table class="truth-table"><thead><tr><th>Question</th><th>Prototype evidence</th><th>Status</th></tr></thead><tbody>${[
 ['Can users distinguish Request, Booking and Stay?','Marketplace truth cards + Host confirmation panel','DEMONSTRATED'],['Is ACCEPTED visibly different from Booking CONFIRMED?','Host decision and Booking conditions remain separate','DEMONSTRATED'],['Is Payment UNKNOWN safe and understandable?','Admin reconciliation with duplicate-action protection','DEMONSTRATED'],['Can Guest access Stay without mandatory account?','Guest Stay Access credential path','DEMONSTRATED'],['Is arrival observation distinct from Check-in?','Butler actions require observation before authorization','DEMONSTRATED'],['Can Inventory Conflict show no winner?','Calendar + conflict entry with competing truths','DEMONSTRATED'],['Does External Accommodation avoid fake commerce?','External Report → Fact → Commitment → Stay path','DEMONSTRATED'],['Does Attention remain a projection?','Attention items link to underlying truth','DEMONSTRATED'],['Does accepted F2 language survive density?','Calendar, operational cards and neutral domain state','DEMONSTRATED']].map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${status(x[2],'current')}</td></tr>`).join('')}</tbody></table></div>
 <div class="grid two"><div class="card"><div class="label">Known simulated behavior</div><p>Authority checks, payment outcomes, external validation, Inventory implication and Stay transitions are local deterministic state changes. No network, payment provider or identity system is connected.</p></div><div class="card"><div class="label">Known limitations / TBDs</div><p>Credential mechanism, expiry/revocation, exact payment economics, conflict resolution procedure, evidence standards, notifications and responsive production breakpoints remain open.</p></div></div>`; }
function render(){
 const views={marketplace,property, 'start-request':()=>requestComposer('Direct'), host, sale, guest, butler, destination, admin, validation};
 $('#main-content').innerHTML=(views[state.view]||marketplace)();
 document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));
 $('#rail-context').textContent=state.view==='host'?'Host · Villa 03':state.view==='sale'?'Sale · SA-014':state.view==='butler'?'Butler · Oceanami':state.view==='destination'?'BQL · Oceanami':state.view==='admin'?'Admin · reconciliation':state.view==='guest'?'Guest · Stay Access':'Guest · Oceanami';
 document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{state.view=x.dataset.view;render()}));
 document.querySelectorAll('[data-action]').forEach(x=>x.addEventListener('click',()=>{if(x.disabled)return; action(x.dataset.action)}));
}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
function action(a){
 switch(a){
  case 'reset': Object.assign(state,{view:'marketplace',context:'Guest · Oceanami',request:{id:'RQ-104',source:'Direct',status:'NONE',hostDecision:'PENDING'},payment:{status:'NOT_STARTED'},booking:{status:'NONE'},stay:{status:'NONE',readiness:'NOT_READY',arrival:'NOT_OBSERVED',checkout:false,completion:false},access:{mode:'credential',account:false},saleRequestCreated:false,incident:{status:'NONE'},hold:{status:'NONE',revalidated:false},external:{reported:false,fact:false,commitment:false,stay:false},conflict:{resolved:false}});toast('Prototype reset to deterministic baseline');break;
  case 'validation':state.view='validation';break;
  case 'property':state.view='property';break;
  case 'marketplace':state.view='marketplace';break;
  case 'host':state.view='host';break;
  case 'sale':state.view='sale';break;
  case 'guest':state.view='guest';break;
  case 'butler':state.view='butler';break;
  case 'destination':state.view='destination';break;
  case 'admin':state.view='admin';break;
  case 'start-request':state.view='start-request';break;
  case 'create-request':state.request.status='CREATED';state.request.source='Direct';state.view='host';toast('RQ-104 created. No Inventory reservation and no Booking created.');break;
  case 'sale-request':state.request.status='CREATED';state.request.source='Sale';state.saleRequestCreated=true;state.view='host';toast('Sale-assisted RQ-104 created. Attribution did not inherit Host authority.');break;
  case 'accept-request':state.request.hostDecision='ACCEPTED';state.request.status='ACCEPTED';toast('Host decision recorded: ACCEPTED. Booking remains UNCONFIRMED.');break;
  case 'reject-request':state.request.hostDecision='REJECTED';state.request.status='REJECTED';toast('Request rejected. No Booking or Stay was created.');break;
  case 'evaluate-confirmation': if(state.request.hostDecision==='ACCEPTED'&&state.payment.status==='SUCCEEDED'){state.booking.status='CONFIRMED';state.stay.status='SCHEDULED';toast('Confirmation conditions pass: Booking CONFIRMED; Stay SCHEDULED.')}else if(state.payment.status==='UNKNOWN'){toast('Cannot confirm: Payment UNKNOWN is not a proven condition.')}else{toast('Cannot confirm: applicable confirmation conditions remain unproven.')}break;
  case 'payment-unknown':state.payment.status='UNKNOWN';toast('Payment UNKNOWN recorded. Duplicate payment action is blocked.');break;
  case 'payment-success':state.payment.status='SUCCEEDED';toast('Payment interaction outcome recorded: SUCCEEDED. Booking is still condition-bound.');break;
  case 'access-credential':state.access.mode='credential';toast('Scoped Stay Access selected. Account not required.');break;
  case 'access-identity':state.access.mode='identity';toast('Authenticated Guest Identity projection selected.');break;
  case 'ready':if(state.stay.status==='SCHEDULED'){state.stay.readiness='READY';toast('READY milestone recorded; Stay remains operationally separate.')}else toast('READY requires a SCHEDULED Stay.');break;
  case 'arrival':if(state.stay.status==='SCHEDULED'){state.stay.arrival='OBSERVED';toast('Arrival OBSERVED recorded as evidence; Check-in not automatic.')}else toast('Arrival observation requires a SCHEDULED Stay.');break;
  case 'checkin':if(state.stay.status==='SCHEDULED'&&state.stay.arrival==='OBSERVED'){state.stay.status='CHECKED_IN';toast('Authorized Check-in recorded.')}else toast('Check-in requires a SCHEDULED Stay, arrival observation and current authority.');break;
  case 'checkout':if(state.stay.status==='CHECKED_IN'){state.stay.checkout=true;state.stay.status='CHECKED_OUT';toast('Authorized Checkout recorded. Completion remains a separate evaluation.')}break;
  case 'complete':if(state.stay.checkout){state.stay.completion=true;state.stay.status='COMPLETED';toast('Completion evaluated. Inventory release is not inferred.')}break;
  case 'did-not-occur':if(state.stay.status==='NONE'||state.stay.status==='SCHEDULED'){state.stay.status='DID_NOT_OCCUR';toast('Explicit authorized DID_NOT_OCCUR evaluation recorded.')}break;
  case 'incident':state.incident.status='OPEN';toast('Operational observation recorded as Incident/evidence. Inventory did not mutate automatically.');break;
  case 'hold':if(state.hold.status==='NONE'){state.hold.status='OPEN';toast('Emergency Protective Hold created with protective attention.')}break;
  case 'revalidate':state.hold.revalidated=true;toast('Protective Hold revalidation recorded; duration remains a TBD.');break;
  case 'resolution':if(!state.conflict.resolved)toast('Conflict entry remains unresolved: no universal precedence selected.');break;
  case 'external-report':state.external.reported=true;toast('External Report / Evidence recorded. No Stayora commerce created.');break;
  case 'external-fact':if(state.external.reported){state.external.fact=true;toast('External Accommodation Fact validated with provenance.')}break;
  case 'external-commitment':if(state.external.fact){state.external.commitment=true;toast('Inventory implication recorded as External-backed Commitment.')}break;
  case 'external-stay':if(state.external.commitment){state.external.stay=true;toast('Legitimate Stay projection created without Stayora Booking.')}break;
 }
 render();
}
render();
